services:
  gateway:
    image: nginx:stable
    "x-google-cloudrun:ingress-container": true
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./portal:/usr/share/nginx/html:ro
    depends_on:
      - inscripcion-ferias
      - ia

  inscripcion-ferias:
    build:
      context: ./demos/inscripcion-ferias
    expose:
      - "5001"

  ia:
    build:
      context: ./demos/ia
    expose:
      - "5000"
