user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    upstream inscripcion_ferias {
        server inscripcion-ferias:80;
    }

    upstream ia_demo {
        server ia:5000;
    }

    server {
        listen 80;
        server_name _;
        absolute_redirect off;
        server_name_in_redirect off;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /demos/inscripcion-ferias {
            return 301 /demos/inscripcion-ferias/;
        }

        location ^~ /demos/inscripcion-ferias/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://inscripcion_ferias/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location = /demos/ia {
            return 301 /demos/ia/;
        }

        location ^~ /demos/ia/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://ia_demo/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

    }
}
